config/routes.rb
Rails.application.routes.draw do

  get '/products_set_aside/:id', to: 'products#set_aside', as: 'products_set_aside'
  get '/products/publications', to: 'products#publications'
  get '/products/sold', to: 'products#sold'
  get '/products/reserved', to: 'products#reserved'
  devise_for :users
  resources :products do 
    resources :comments
  end
  root to: 'products#index'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    has_one_attached :picture
    has_many :comment, dependent: :destroy
    validates :name, presence: true, length: { minimum: 5 }
    validates :description, presence: true
    validates :picture, presence: true

    def self.search(search)
        if search
            where(["name LIKE ?", "%#{search}%"])
        else
            all
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comment.create(params[:comment].permit(:name, :body))

    redirect_to product_path(@product)
  end

  def destroy
    @product = Product.find(params[:product_id])
    @comment = @product.comment.find(params[:id])
    @comment.destroy

    redirect_to product_path(@product)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!, only: [:edit, :update, :new, :set_aside, :create, :show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.where(enabled:true)
    @products = Product.search(params[:search])
  end

  def set_aside
    @product = Product.find(params[:id])
    @product.enabled = false
    @product.reserved = current_user.id
    @product.save

    redirect_to root_path, notice: "HAS RESERVADO EL PRODUCTO"
  end
  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  def reserved
    @products = Product.where(enabled:false)
  end
  
  def sold
    @products = Product.where(enabled:false)
  end

  def publications
    @publications = Product.all
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user = current_user

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :enabled, :picture, :user_id, :reserved, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix my-5 mb-5">
    <div class="comment_content">
        <p class="comment_name"><em><%= comment.name %></em></p>
        <p class="comment_body"><%= comment.body %></p>
        <p class="comment_title"><%= time_ago_in_words(comment.created_at) %>Ago</p>
        <div class="container mx-auto d-flex my-4">
          <div class="border-bottom w-100"></div>
        </div>
    </div>
    <p class="my-5"> <%= link_to 'Delete', [comment.product, comment], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?'} %></p>

</div>

app/views/comments/_form.html.erb
<%= form_for([@product, @product.comment.build]) do |f|%>
    <form class="form-inline" role="form">


          <div class="form-group">
            <%= f.label :name %><br>
            <%= f.text_field :name, class: "form-control bg-white border-left-0 border-md"%>
          </div>

          <div class="form-group">
            <%= f.label :body %><br>
            <%= f.text_area :body, class: "form-control bg-white border-left-0 border-md"%>
          </div>
                <%= f.submit "Enviar", class: "btn btn-primary" %>
            </p>
        <% end %>
    </form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pertmutapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://use.fontawesome.com/e48058af53.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Yanone+Kaffeesatz:wght@400;600;700&display=swap" rel="stylesheet">
  </head>

  <body style="margin-top:120px;">
    <%= render "shared/navbar" %>
    <!--devise alert-->
    <% if notice %>
      <p class="notice alert-primary"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <div class="container-fluid">
      <%= yield %>
    </div>

    
    <%= render  "shared/footer"%>
   

  <!--Bootstrap-->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
  </body>
</html>

app/views/products/_form.html.erb
<div class="text-center">
<%= form_with(model: product, local: true, class: "form-horizontal") do |form| %>
  <% if product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
  
    <ul>
      <% product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  
  <div class="form-group my-5 text-center">
    <%= form.label :name, "Título", class: "col-lg-2 control-label" %>
    <div class="col-lg-10" >
      <%= form.text_field :name, id: :product_name %>
    </div>
  </div>
  
  <div class="form-group my-5 form-group-custom">
    <%= form.label :picture, "URL Imagen", class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= image_tag(product.picture, style: "margin-bottom: 10px; border-radius: 5px;") if product.picture? %>
  
      <%= form.file_field :picture, id: :product_picture, class: "form-control" %>
    </div>
    <%= form.hidden_field :picture_cache %>
  </div>
</div>

<div class="form-group my-5">
  <%= form.label :description, "Descripción", class: "col-lg-2 control-label" %>
  <div class="col-lg-10">
    <%= form.text_area :description, id: :product_content, class: "form-control", rows: 10 %>
  </div>
</div>

<div class="field">
  <%= form.label :enabled, "Disponible" %>
  <%= form.check_box :enabled, id: :product_enabled %>
</div>

<div class="form-group my-5">
  <div class="col-lg-10 col-lg-offset-2">
      <%= form.submit "Enviar", class: "btn btn-primary" %>
      <%= link_to 'Volver', products_path, class: "btn btn-warning"  %>      
      <%= link_to 'Editar Mis Productos', products_publications_path, class: "btn btn-success"  %>
    <% end %>
  </div>
</div>
<fieldset>  
</div>

app/views/products/edit.html.erb
<div class="text-center">
  <h1>Editar Productos</h1>

  <%= render 'form', product: @product %>

</div>

app/views/products/index.html.erb
<div class="row">
<section >
  <!--carousel-->
  <div class="container my-3">
  <div class="col-xs-8 col-sm-10 col-md-10">
    <h1 class="text-center text-secondary">BIENVENIDOS AL MUNDO DEL CANJE</h1>
  </div>
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
      <ol class="carousel-indicators">
        <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"></li>
        <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"></li>
        <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"></li>
      </ol>
      <div class="carousel-inner bg-dark">
        <div class="carousel-item active">
          <img src="https://www.superprof.cl/blog/wp-content/uploads/2019/01/cuerdas-guitarra.jpg" class="d-block w-100 fixed-height" alt="...">
          <div id="lol" class="carousel-caption d-md-block bg-dark opacity-3">
            <strong>
              <h4>PertmutApp</h4>
              <p>¡En <b>PertmutApp</b> te ayudamos a encontrar eso que tanto quieres!.</p>
            </strong>
          </div>
        </div>
        <div class="carousel-item bg-dark">
          <img src="https://as01.epimg.net/deporteyvida/imagenes/2019/11/03/portada/1572798603_458091_1572798763_noticia_normal_recorte1.jpg" class="d-block w-100 fixed-height" alt="...">
          <div class="carousel-caption d-md-block bg-dark opacity-3">
            <strong>  
              <h4>¿No lo necesitas?</h4>
              <p>¡Anuncia tu producto y cambialo por otro! </p>
            </strong>
          </div>
        </div>
        <div class="carousel-item">
          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7R28TGTVticikPBbhwXhjF1FdV1SSctSieg&usqp=CAU" class="d-block w-100 fixed-height" alt="...">
          <div class="carousel-caption d-md-block bg-dark opacity-3">
            <strong>
              <h4>Busca lo que necesitas</h4>
              <p>¡No hay forma de perder! ¡Ganamos todos!.</p>
            </strong>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </a>
    </div>
  </div>
</section>
<br>
<div class="container mx-auto d-flex my-4">
  <div class="border-bottom w-100"></div>
</div>
<br>
<section class="container d-md-block" style="background-color: blanchedalmond;">
<div class="">
  <h1 class="text-center my-5">PERTMUTAPP</h1>
  <div class="row">
    <div class="col-lg-5">
      <img  class="w-100 mb-4 border border-md border-white shadow-sm" src="<%= asset_path 'logo.jpg' %>">
    </div>
    <div class="col-lg-7">

      <h4 class=" text-justify"> PertmutApp es una App creada para ayudar a comunicar y realizar canjes entre las personas que residencen actualmente en Santiago-Region Metropolitana y se han visto afectado por el COVID-19.</h4>
      <br>
      <h4 class=" text-justify"> Contamos con una amplia variedad de productos que son publicados por todas las personas que desean cambiar algo que no utilicen por otro objeto que deseen.</h4>
      <br>
      <h4 class=" text-justify"> Es importante destacar que PertmutApp no realiza cobros en ningun momento, es una inicitiva sin fines de lucros.</h4>
      <br>
      <h4 class=" text-justify ">Ya que nuestros servicios son gratuitos cualquier usuario podra registrarse y podra realizar transacciones a cualquier hora del día con otros usuarios</h4>
      <br>
      <h4 class=" text-justify ">PertmutApp te invita publicar y conocer el mundo del intercambio de bienes que ya no tienen valores para ti por alguno que consideres interesante!!!! APRESURATE Y COMIENZA A PUBLICAR YA!!!!</h5>
    </div>
  </div>
</div>

</section>

<div class="container mx-auto d-flex my-4">
  <div class="border-bottom w-100"></div>
</div>
<section>
  <h1 class="text-center my-5">ARTICULOS DISPONIBLES</h1>
    <div class="row my-5">
      <% @products.each do |product| %>
        <% if product.enabled == true %>
        <div class="col-sm-4">
          <div class="thumbnail">
              <div class="caption text-center text-justify">
              <h3><%= image_tag product.picture.variant(resize: "200x200") %></h3>
              <h3> <%= product.name %></h3>
              <h5 style="text-align:justify;"><%= product.description %></h3>
              <p><small><%= time_ago_in_words(product.created_at) %> ago</small></p>
              <%= link_to 'Ver Producto', product, class: "btn btn-warning"  %>
              </div>
            </div>
          </div>
          <% end %>
        <% end %>
    </div>
</section>

app/views/products/new.html.erb
<div class="text-center my-5">
    <h1>Nuevo Producto</h1>
</div>

<div class="container">
    <%= render 'form', product: @product %>
</div>

app/views/products/offer.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-xs-8 col-sm-10 col-md-10">
    <h1 class="text-center text-secondary">Productos</h1>
  </div>

  <div class="text-letf">
    <%= link_to 'Volver', products_path, class: "btn btn-warning"  %>
  </div>


  <div class="row">
    <% @products.each do |product| %>
    <div class="col-sm-4">
      <div class="thumbnail">
        <figure>

        </figure>


        <div class="caption text-center">

          <h3>  <%= product.name %></h3>

          <h3><%= product.description %></h3>



          <p><small><%= time_ago_in_words(product.created_at) %> ago</small></p>


          <%= link_to 'Edit', edit_product_path(product), class: "btn btn-succes" %>
          <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-info" %>

          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>

app/views/products/profile.html.erb
<div class="text-center">
  <h1>Perfil</h1>

  <div class="row row-main-custom">
    <p>Nombre <%= @user.name %></p>
    <p>Email <%= @user.email %></p>
  </div>
</div>

app/views/products/publications.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-xs-8 col-sm-10 col-md-10">
    <h1 class="text-center text-secondary">Mis Productos Publicados</h1>
  </div>

  <div class="row">
    <% @publications.each do |product| %>
      <% if user_signed_in? && (current_user.id == product.user_id) %>
    <div class="col-sm-4 my-5">
      <div class="thumbnail">
        <div class="caption text-center">
          <h3>  <%= product.name %></h3>
          <h3 style="text-align: justify;"><%= product.description %></h3>
          <h5><%= image_tag product.picture.variant(resize: "200x200") %></h5>
          <p><small><%= time_ago_in_words(product.created_at) %> ago</small></p>
          <%= link_to 'Editar', edit_product_path(product), class: "btn btn-success" %>
          <%= link_to 'Eliminar', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
    <div class="text-letf">
  </div>
  </div>

app/views/products/reserved.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-xs-8 col-sm-10 col-md-10">
    <h1 class="text-center text-secondary">Mis Productos Reservados</h1>
  </div>


  <div class="row my-5">
    <% @products.each do |product| %>
    <%  if product.enabled == false && product.reserved == current_user.id%>
    <div class="col-sm-4">

      <div class="thumbnail">
       <div class="caption text-center">
          <%= image_tag product.picture.variant(resize: "200x200") %>
          <div class="caption text-center">
            <h3>  <%= product.name %></h3>
            <h5 style="text-align:justify;"><%= product.description %></h5>
            <p><small><%= time_ago_in_words(product.created_at) %> ago</small></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>

app/views/products/show.html.erb
<div class="text-center">
  <p id="notice"><%= notice %></p>
<div class="publication">
  <div class="card" style="width: 40rem;">
  <%= image_tag @product.picture.variant(resize: "200x200") %>
    <div class="card-body">
      <h5 class="card-title"><%= @product.name %></h5>
      <p class="card-text"><%= @product.description %></p>
      <p class="card-text"><%= @product.enabled %></p>
      <%= link_to 'Reservar Producto', products_set_aside_path(@product), class: "btn btn-success"  %>
      <% if current_user.id == @product.user_id %>
        <%= link_to 'Editar', edit_product_path(@product),class: "btn btn-info" %>
      <% end %>
    </div>
  </div>
</div>
</div>
<br>
<div class="container mx-auto d-flex my-4">
  <div class="border-bottom w-100"></div>
</div>
<br>
<div id="comments" class="container">
        <h2><%= @product.comment.count %> Comments</h2>
        <%= render @product.comment %>
        <h3 class="my-5"> Join Discussion:</h3>
        <%= render "comments/form" %>
</div>

app/views/products/sold.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-xs-8 col-sm-10 col-md-10">
    <h1 class="text-center text-secondary">Productos por Entregar</h1>
  </div>

<div class="container mx-5">
  <div class="row">
    <% @products.each do |product| %>
      <% if user_signed_in? && (current_user.id == product.user_id) %>
    <div class="col-sm-4 my-5">
      <div class="caption text-center">

        <div class="thumbnail">
          <h3><%= image_tag product.picture.variant(resize: "200x200") %></h3>
          <div class="caption text-center">
            <h3>  <%= product.name %></h3>
            <h5 style="text-align:justify;"><%= product.description %></h5>
            <p><small><%= time_ago_in_words(product.created_at) %> ago</small></p>
            <%= link_to 'Edit', edit_product_path(product), class: "btn btn-success" %>
            <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-info" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="container-fluid colordark text-white letra" style="margin-top:150px;">
  <div class="row">
    <div class="col-md-4" >
      <p class="text-center"><%= image_tag 'logo_size_invert.jpg', class: "logo"%></p>
      <h2 class="text-uppercase font-weight-bold mb-4 text-center">No dejes Pasar la Oportunidad</h2>
  </div>

    <div class="col-md-4 mt-5 d-none d-sm-none d-md-block">
      <h2 class="text-uppercase font-weight-bold mb-4 text-center">Navega</h2>
      <ul class="list-unstyled text-center" >
        <li class="mb-2"><a href="/" class="text-white letra"><h3>Inicio</h3></a></li>
        <br>
        <li class="mb-2"><a href="<%= new_product_path %>" class="text-white letra"><h3>Publicar</h3> </a></li>
        <br>
        <li class="mb-2"><a href="<%= products_publications_path  %>" class="text-white letra"><h3>Publicaciones</h3></a></li>
        <br>
      </ul>

    </div>

    <div class="col-md-4 mt-4">
    <div class="col-md-4" >
      <p><%= image_tag 'logo_size_invert.jpg', class: "logo"%></p>
      <h2 class="text-uppercase font-weight-bold mb-4">Encuentralo!</h2>
    </div>
  </div>


  <!-- Copyrights -->
  <div >
    <div class="container text-center text-white letra">
      <p class="mb-0 py-2">© 2021 PERTMUTAPP donde encontrarás los que necesitas en Santiago.</p>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<% if current_user %>
<!--Usuario logueado-->
<nav class="navbar navbar-expand-lg navbar-light bg-dark fixed-top ">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon white"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a id="test" class="nav-link active text-white" aria-current="page" href="/"><%= image_tag 'logo_size_invert.jpeg', class: 'img-navbar'%> PERTMUTAPP</h2></a>
        </li>
      </ul>
      <form class="navbar-nav text-white ">
        <li class = "nav-item"><%= render  "shared/search"%></li>
        <li class="nav-item active"><a class=" nav-link text-white letra" href="/">Inicio|</a></li>
        <li class="nav-item"><a class=" nav-link text-white letra" href="<%= new_product_path %>">Publicar|</a></li>
        <li class="nav-item"><a class=" nav-link text-white letra" href="<%= products_publications_path %>">Publicaciones|</a></li>
        <li class="nav-item"><a class=" nav-link text-white letra" href="<%= products_reserved_path %>">Mis Cambios|</a></li>
        <li class="nav-item"><a class=" nav-link text-white letra" href="<%= products_sold_path %>">Mi Trueques|</a></li>
        <li class="nav-item"><a class=" nav-link text-white letra" href="<%= edit_user_registration_path %>">Mi Perfil|</a></li>
        <li class="nav-item"><a href="<%= destroy_user_session_path %>" data-method="DELETE">Cerrar Sesión|</a></li>
        <li class="nav-item"><a class=" nav-link text-white letra"><%= current_user.email %></a></li>
      </form>
    </div>
  </div>
</nav>
<%else%>
<!--Usuario no logueado-->
<nav class="navbar navbar-expand-lg navbar-light bg-dark fixed-top">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon white"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <a id="test" class="nav-link active text-white" aria-current="page" href="/"><%= image_tag 'logo_size_invert.jpeg', class: 'img-navbar'%> PERTMUTAPP</h2></a>        </li>
      </ul>
      <form class="navbar-nav ">
        <li class = "nav-item"><%= render  "shared/search"%></li>
        <li class="nav-item active"><a class=" nav-link text-white letra" href="/">Inicio|</a></li>
        <li class="nav-item"><a class=" nav-link text-white letra" href="<%= new_product_path %>">Publicar|</a></li>
        <li class="nav-item"><a class=" nav-link text-white letra" href="<%= new_user_registration_path %>">Registrarse|</a></li>
        <li class="nav-item"><a class=" nav-link text-white letra" href="<%= new_user_session_path %>">Ingresar|</a></li>
      </form>
    </div>
  </div>
</nav>
<%end%>

app/views/shared/_search.html.erb
<%= form_tag products_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", class: "botton_search" %>
<% end %>